site_name: ZuoRight
site_description: Right is right, left is also right.
site_author: 7c
site_url: https://www.zuoright.com

# repo_name: ZuoRight/zuoright.github.io
# repo_url: https://github.com/ZuoRight/zuoright.github.io

copyright: Copyright &copy; 2016 ~ Forever 7c

theme:
  name: material
  language: zh
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: green
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: green
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    logo: material/read
    # repo: material/source-branch
  favicon: images/favicon.png
  features:
    - header.autohide  # 下滑自动隐藏导航栏
    - navigation.top  # 回到顶部
    - navigation.instant  # 内部锚链接即时加载
    - toc.integrate  # 导航集成到左侧

extra:
  generator: false  # 移除MkDocs链接
  analytics:
    provider: google
    property: G-6CVJ632G5J
    feedback:
      title: 此页面内容可还行？
      ratings:
        - icon: material/thumb-up-outline
          name: 有用的
          data: 1
          note: >-
            感谢反馈，欢迎随时<a href="mailto:zuoright@foxmail.com" target=_blank>发邮件</a>跟我交流
        - icon: material/thumb-down-outline
          name: 没啥用
          data: 0
          note: >- 
            感谢反馈，欢迎<a href="mailto:zuoright@foxmail.com" target=_blank>发邮件</a>给我提出改进建议
  social:  # 右下角社交图标和链接
    - icon: material/github
      link: https://github.com/ZuoRight
    - icon: material/email
      link: mailto:zuoright@foxmail.com
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.

markdown_extensions:
  - footnotes  # 支持脚注
  - meta  # 可以添加元信息
  - admonition  # 可以添加提示条
  - pymdownx.highlight  # 高亮
  - pymdownx.inlinehilite
  - pymdownx.keys  # 支持++按键A+按键B++这种语法
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed  # 分组式代码块
  - attr_list  # 支持大按钮
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true  # 固定链接

plugins:
  - search:
      lang:
        - ja
  - git-revision-date-localized:  # 文章底部显示更新时间，需要先安装插件
      type: iso_date
      # enable_creation_date: true  # 显示创建时间
  - glightbox  # 放大图片
  - awesome-pages  # 更方便的设置目录顺序
