site_name: notes
site_description: description
site_author: 7c

# copyright: 1992~Forever 7c. All rights reserved.
# theme:
#     name: mkdocs
#     # custom_dir: my_theme_customizations/

nav:
    - Index: index.md
    - About: about.md
