site_name: notes
site_description: description
site_author: 7c

copyright: copyright
theme:
    name: mkdocs
    # custom_dir: my_theme_customizations/

nav:
    - Index: index.md
    - About: about.md
