name: ci
on:
  push:
    branches:
      - master
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CONFIG_FILE: notes/mkdocs.yml
      - run: pip install mkdocs-material mkdocs-git-revision-date-localized-plugin
      - run: ls -a
      - run: cd notes; ls -a; mkdocs gh-deploy --force
