name: ci bolg test
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - run: |
          pip install mkdocs-material mkdocs-git-revision-date-localized-plugin
          
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          
      - run: |
          cd notes
          mkdocs build
          
      - run: |
          git add .
          git rm -r --cached notes/docs
          git rm -r --cached .github/workflows
          git commit -m "ci commit"
          git push origin master:dev --force
